import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:konektizen/core/localization/app_language.dart';

const _storage = FlutterSecureStorage();
const _languageStorageKey = 'konektizen_language';

final appLanguageProvider =
    StateNotifierProvider<AppLanguageNotifier, AppLanguage>((ref) {
      return AppLanguageNotifier();
    });

final appStringsProvider = Provider<AppStrings>((ref) {
  return AppStrings(ref.watch(appLanguageProvider));
});

class AppLanguageNotifier extends StateNotifier<AppLanguage> {
  AppLanguageNotifier() : super(AppLanguage.english) {
    _load();
  }

  Future<void> _load() async {
    final saved = await _storage.read(key: _languageStorageKey);
    state = AppLanguage.fromCode(saved);
  }

  Future<void> setLanguage(AppLanguage language) async {
    state = language;
    await _storage.write(key: _languageStorageKey, value: language.code);
  }
}

class AppStrings {
  AppStrings(this.language);

  final AppLanguage language;

  String text(String key) =>
      _strings[language]?[key] ?? _strings[AppLanguage.english]?[key] ?? key;
}

const _strings = {
  AppLanguage.english: {
    'nav.home': 'Home',
    'nav.sos': 'SOS',
    'nav.map': 'Map',
    'nav.advisory': 'Advisory',
    'nav.profile': 'Profile',
    'home.greeting': 'Good Morning',
    'home.quickReport': 'Report an Issue',
    'home.category.garbage': 'Garbage',
    'home.category.road': 'Road',
    'home.category.flood': 'Flood',
    'home.category.streetLight': 'Street Light',
    'home.category.traffic': 'Traffic',
    'home.category.report': 'Report',
    'home.alertsNews': 'Alerts and News',
    'home.alertsNotifications': 'Alerts & Notifications',
    'home.newsSources': 'News Sources',
    'home.activeReports': 'Active Reports',
    'home.viewAll': 'View All',
    'home.noActiveReports': 'No active reports',
    'home.checkHistory': 'Check History',
    'profile.title': 'Profile',
    'profile.verified': 'Verified Citizen',
    'profile.pending': 'Verification Pending',
    'profile.notVerified': 'Not Verified',
    'profile.verifyAccount': 'Verify Your Account',
    'profile.verifySubtitle': 'Get verified to help your barangay.',
    'profile.verificationProgress': 'Verification In Progress',
    'profile.verificationProgressSubtitle': 'We are checking your documents.',
    'profile.edit': 'Edit Profile',
    'profile.myCases': 'My Cases',
    'profile.language': 'Language',
    'profile.accessibility': 'Accessibility',
    'profile.help': 'Help & Support',
    'profile.about': 'About KONEKTIZEN',
    'profile.logout': 'Log Out',
    'profile.chooseLanguage': 'Choose Language',
    'cases.title': 'My Cases',
    'cases.active': 'Active',
    'cases.inProgress': 'In Progress',
    'cases.history': 'History',
    'cases.empty': 'No cases found',
    'report.title': 'Report a Problem',
    'report.cancel': 'Cancel',
    'report.next': 'Next',
    'report.back': 'Back',
    'report.confirm': 'Confirm & Continue',
    'report.changeCategory': 'Change Category',
    'report.submit': 'Submit Report',
    'report.gpsConfirm': 'Confirm This Location',
    'report.gpsUpdate': 'Update Location',
    'report.stepDescription': 'Describe the Problem',
    'report.stepDescriptionSubtitle': 'Tell us what happened. The AI will help categorize it.',
    'report.placeholderBasura': 'Example: "There is a pile of garbage on the side of the road..."',
    'report.placeholderKalsada': 'Example: "There is a large pothole on Rizal Street..."',
    'report.placeholderPagbaha': 'Example: "There is deep flooding on Quezon Street..."',
    'report.placeholderIlaw': 'Example: "The street light on Aurora Boulevard is broken..."',
    'report.placeholderTrapiko': 'Example: "Heavy traffic on EDSA due to broken traffic light..."',
    'report.placeholderDefault': 'Example: "Describe the issue in your area and where it is located..."',
    'report.analyzing': 'Analyzing...',
    'report.analyzingSubtitle': 'AI is analyzing your report...',
    'report.pleaseWait': 'Please wait a moment.',
    'report.error': 'Error Occurred',
    'report.tryAgain': 'Try Again',
    'report.aiComplete': 'AI Analysis Complete',
    'report.aiGuess': 'Based on your description, this looks like:',
    'report.urgency': 'Urgency',
    'report.detectedCity': 'Detected City',
    'report.isCorrect': 'Is this correct?',
    'report.selectCategory': 'Select Category',
    'report.evidenceTitle': 'Evidence & Location',
    'report.searchLocation': 'Search location...',
    'report.tapMap': 'Tap on the map to select location',
    'report.gpsAutoLocked': 'Location automatically locked to your GPS for accurate reporting.',
    'report.evidenceLabel': 'Evidence',
    'report.photoButton': 'Photo',
    'report.videoButton': 'Video',
    'report.evidenceRequired': 'A photo or video is required as evidence.',
    'report.failedUpload': 'Failed to upload evidence. Please check connection and try again.',
    'report.reviewTitle': 'Review Report',
    'report.summary': 'Summary',
    'report.fieldProblem': 'Problem',
    'report.fieldUrgency': 'Urgency/Severity',
    'report.fieldReportedLocation': 'Reported Location',
    'report.fieldYourLocation': 'Your Exact Location',
    'report.fieldDescription': 'Description',
    'report.evidenceCount': 'Evidence',
    'report.noEvidence': 'No evidence attached',
    'report.locationVerification': 'Location Verification',
    'report.gpsVerificationRequired': 'GPS verification is required before submission. Click below to confirm.',
    'report.verifiedLocationLabel': 'Verified Location:',
    'report.certifyText': 'I certify that this information is true and correct and I allow to send my exact location.',
    'report.gpsEnableToSubmit': 'Enable GPS to Submit',
    'report.gpsRequiredTitle': 'Location Required',
    'report.gpsRequiredBody': 'To submit a report, Konektizen needs your location for accurate routing and response.',
    'report.gpsTurnOnTitle': 'Turn on GPS',
    'report.gpsTurnOnBody': 'Please turn on Location Services (GPS) to continue.',
    'report.successTitle': 'Report Submitted!',
    'report.caseLabel': 'Case',
    'report.expectedResponse': 'Expected Response Time',
    'report.responseTimeValue': '24-48 Hours',
    'report.thankYou': 'Thank you for being an active citizen.',
    'report.backHome': 'Back to Home',
    'report.tapToSpeak': 'Tap to Speak',
    'report.listening': 'Listening...',
  },
  AppLanguage.tagalog: {
    'nav.home': 'Tahanan',
    'nav.sos': 'SOS',
    'nav.map': 'Mapa',
    'nav.advisory': 'Abiso',
    'nav.profile': 'Profile',
    'home.greeting': 'Magandang umaga',
    'home.quickReport': 'Mag-ulat ng Isyu',
    'home.category.garbage': 'Basura',
    'home.category.road': 'Kalsada',
    'home.category.flood': 'Pagbaha',
    'home.category.streetLight': 'Ilaw sa Kalye',
    'home.category.traffic': 'Trapiko',
    'home.category.report': 'Mag-ulat',
    'home.alertsNews': 'Mga Abiso at Balita',
    'home.alertsNotifications': 'Mga Abiso at Notipikasyon',
    'home.newsSources': 'Pinagmumulan ng Balita',
    'home.activeReports': 'Aktibong mga Ulat',
    'home.viewAll': 'Tingnan Lahat',
    'home.noActiveReports': 'Walang aktibong ulat',
    'home.checkHistory': 'Suriin ang History',
    'profile.title': 'Profile',
    'profile.verified': 'Beripikadong Mamamayan',
    'profile.pending': 'Naka-pending ang Beripikasyon',
    'profile.notVerified': 'Hindi Pa Beripikado',
    'profile.verifyAccount': 'I-verify ang Account',
    'profile.verifySubtitle': 'Magpa-verify para makatulong sa barangay.',
    'profile.verificationProgress': 'Kasalukuyang Bine-verify',
    'profile.verificationProgressSubtitle':
        'Sinusuri namin ang iyong mga dokumento.',
    'profile.edit': 'I-edit ang Profile',
    'profile.myCases': 'Aking mga Kaso',
    'profile.language': 'Wika',
    'profile.accessibility': 'Accessibility',
    'profile.help': 'Tulong at Suporta',
    'profile.about': 'Tungkol sa KONEKTIZEN',
    'profile.logout': 'Mag-log Out',
    'profile.chooseLanguage': 'Pumili ng Wika',
    'cases.title': 'Aking mga Kaso',
    'cases.active': 'Aktibo',
    'cases.inProgress': 'Ginagawa',
    'cases.history': 'History',
    'cases.empty': 'Walang nakitang kaso',
    'report.title': 'Mag-ulat ng Problema',
    'report.cancel': 'Kanselahin',
    'report.next': 'Susunod',
    'report.back': 'Bumalik',
    'report.confirm': 'Kumpirmahin at Magpatuloy',
    'report.changeCategory': 'Baguhin ang Kategorya',
    'report.submit': 'Isumite ang Ulat',
    'report.gpsConfirm': 'Kumpirmahin ang Lokasyon',
    'report.gpsUpdate': 'I-update ang Lokasyon',
    'report.stepDescription': 'Ilarawan ang Problema',
    'report.stepDescriptionSubtitle': 'Sabihin sa amin ang nangyari. Tutulungan ka ng AI na ikategorya ito.',
    'report.placeholderBasura': 'Halimbawa: "May tambak ng basura sa gilid ng kalsada malapit sa barangay hall."',
    'report.placeholderKalsada': 'Halimbawa: "May malaking butas sa kalsada sa Rizal Street na nagiging sanhi ng trapiko."',
    'report.placeholderPagbaha': 'Halimbawa: "May mataas na baha sa Quezon Street na hindi madaanan ng sasakyan."',
    'report.placeholderIlaw': 'Halimbawa: "Patay ang ilaw sa kalye sa Aurora Boulevard kaya delikado sa gabi."',
    'report.placeholderTrapiko': 'Halimbawa: "Matinding trapiko sa EDSA dahil sa sirang traffic light."',
    'report.placeholderDefault': 'Halimbawa: "Ilarawan ang problema sa inyong lugar at kung saan ito nangyari."',
    'report.analyzing': 'Sinusuri...',
    'report.analyzingSubtitle': 'Sinusuri ng AI ang iyong ulat...',
    'report.pleaseWait': 'Sandali lang po.',
    'report.error': 'May Error',
    'report.tryAgain': 'Subukan Muli',
    'report.aiComplete': 'Kumpleto ang Pagsusuri ng AI',
    'report.aiGuess': 'Batay sa iyong paglalarawan, ito ay mukhang:',
    'report.urgency': 'Urgency',
    'report.detectedCity': 'Detected City',
    'report.isCorrect': 'Tama ba ito?',
    'report.selectCategory': 'Pumili ng Kategorya',
    'report.evidenceTitle': 'Ebidensya at Lokasyon',
    'report.searchLocation': 'Maghanap ng lokasyon...',
    'report.tapMap': 'I-tap ang mapa para pumili ng lokasyon',
    'report.gpsAutoLocked': 'Awtomatikong nakatutok ang lokasyon sa iyong GPS para sa mas tumpak na ulat.',
    'report.evidenceLabel': 'Ebidensya',
    'report.photoButton': 'Larawan',
    'report.videoButton': 'Video',
    'report.evidenceRequired': 'Kailangan ng litrato o video bilang ebidensiya.',
    'report.failedUpload': 'Bigo sa pag-upload ng ebidensya. Pakisuri ang koneksyon at subukan muli.',
    'report.reviewTitle': 'Suriin ang Ulat',
    'report.summary': 'Buod',
    'report.fieldProblem': 'Problema',
    'report.fieldUrgency': 'Urgency/Severity',
    'report.fieldReportedLocation': 'Iniulat na Lokasyon',
    'report.fieldYourLocation': 'Iyong Eksaktong Lokasyon',
    'report.fieldDescription': 'Deskripsyon',
    'report.evidenceCount': 'Ebidensya',
    'report.noEvidence': 'Walang nakalakip na ebidensya',
    'report.locationVerification': 'Kumpirmahin ang Lokasyon',
    'report.gpsVerificationRequired': 'Kailangan ng GPS verification bago makapag-submit. I-click ang button sa ibaba upang kumpirmahin.',
    'report.verifiedLocationLabel': 'Beripikadong Lokasyon:',
    'report.certifyText': 'Pinapatunayan ko na ang impormasyong ito ay totoo at tama at pinapayagan kong ipadala ang aking eksaktong lokasyon.',
    'report.gpsEnableToSubmit': 'I-enable ang GPS para Isumite',
    'report.gpsRequiredTitle': 'Kailangan ang Lokasyon',
    'report.gpsRequiredBody': 'Upang makapag-submit ng report, kailangan ng Konektizen ang iyong lokasyon for accurate routing and response.',
    'report.gpsTurnOnTitle': 'Buksan ang GPS',
    'report.gpsTurnOnBody': 'Mangyaring buksan ang Location Services (GPS) upang magpatuloy.',
    'report.successTitle': 'Naisumite ang Ulat!',
    'report.caseLabel': 'Kaso',
    'report.expectedResponse': 'Inaasahang Oras ng Tugon',
    'report.responseTimeValue': '24-48 Oras',
    'report.thankYou': 'Salamat sa pagiging aktibong mamamayan.',
    'report.backHome': 'Bumalik sa Home',
    'report.tapToSpeak': 'Pindutin para Magsalita',
    'report.listening': 'Nakikinig...',
  },
  AppLanguage.ilocano: {
    'nav.home': 'Balay',
    'nav.sos': 'SOS',
    'nav.map': 'Mapa',
    'nav.advisory': 'Pakaammo',
    'nav.profile': 'Profile',
    'home.greeting': 'Naimbag a bigat',
    'home.quickReport': 'Agreport ti Isyu',
    'home.category.garbage': 'Basura',
    'home.category.road': 'Kalsada',
    'home.category.flood': 'Layus',
    'home.category.streetLight': 'Silaw ti Kalsada',
    'home.category.traffic': 'Trapiko',
    'home.category.report': 'Agreport',
    'home.alertsNews': 'Dagiti Pakaammo ken Damag',
    'home.alertsNotifications': 'Dagiti Pakaammo',
    'home.newsSources': 'Pagtaudan ti Damag',
    'home.activeReports': 'Aktibo a Report',
    'home.viewAll': 'Kitaen Amin',
    'home.noActiveReports': 'Awan ti aktibo a report',
    'home.checkHistory': 'Kitaen ti History',
    'profile.title': 'Profile',
    'profile.verified': 'Napaneknekan nga Umili',
    'profile.pending': 'Ur-urayen ti Panangpaneknek',
    'profile.notVerified': 'Saan pay a Napaneknekan',
    'profile.verifyAccount': 'Paneknekan ti Account',
    'profile.verifySubtitle': 'Agpa-verify tapno makatulong iti barangay.',
    'profile.verificationProgress': 'Mapaspasamak ti Panangpaneknek',
    'profile.verificationProgressSubtitle': 'Sursurien mi dagiti dokumentom.',
    'profile.edit': 'Urnosen ti Profile',
    'profile.myCases': 'Dagiti Kasok',
    'profile.language': 'Pagsasao',
    'profile.accessibility': 'Accessibility',
    'profile.help': 'Tulong ken Suporta',
    'profile.about': 'Maipapan iti KONEKTIZEN',
    'profile.logout': 'Ag-log Out',
    'profile.chooseLanguage': 'Pilien ti Pagsasao',
    'cases.title': 'Dagiti Kasok',
    'cases.active': 'Aktibo',
    'cases.inProgress': 'Mapaspasamak',
    'cases.history': 'History',
    'cases.empty': 'Awan ti nakitada a kaso',
    'report.title': 'Agreport ti Problema',
    'report.cancel': 'Ikhansela',
    'report.next': 'Sumaruno',
    'report.back': 'Agsubli',
    'report.confirm': 'Paneknekan ken Ituloy',
    'report.changeCategory': 'Sukatan ti Katigorya',
    'report.submit': 'Isumite ti Report',
    'report.gpsConfirm': 'Paneknekan ti Lokasyon',
    'report.gpsUpdate': 'I-update ti Lokasyon',
    'report.stepDescription': 'Ipalawag ti Problema',
    'report.stepDescriptionSubtitle': 'Ibagam kadakami ti napasamak. Tutulungannaka ti AI a mangikategoria iti daytoy.',
    'report.placeholderBasura': 'Pagarigan: "Adda tambak ti basura iti abay ti kalsada..."',
    'report.placeholderKalsada': 'Pagarigan: "Adda dakkel a banga iti kalsada idiay Rizal Street..."',
    'report.placeholderPagbaha': 'Pagarigan: "Adda naadalem a layus idiay Quezon Street..."',
    'report.placeholderIlaw': 'Pagarigan: "Saan nga agsilsilaw ti silaw ti kalsada idiay Aurora Boulevard..."',
    'report.placeholderTrapiko': 'Pagarigan: "Napigsa a trapiko idiay EDSA gapu ti nadadael a traffic light..."',
    'report.placeholderDefault': 'Pagarigan: "Ipalawag ti problema iti lugaryo ken no sadino ti nagpasamakanna."',
    'report.analyzing': 'Sursurien...',
    'report.analyzingSubtitle': 'Sursurien ti AI ti reportmo...',
    'report.pleaseWait': 'Aguray bassit.',
    'report.error': 'Adda Biddut',
    'report.tryAgain': 'Padasan Manen',
    'report.aiComplete': 'Nalpas ti Panangusig ti AI',
    'report.aiGuess': 'Maibatay iti deskripsionmo, kasla daytoy:',
    'report.urgency': 'Urgency',
    'report.detectedCity': 'Nakitang Ciudad',
    'report.isCorrect': 'Husto kadi daytoy?',
    'report.selectCategory': 'Pilien ti Katigorya',
    'report.evidenceTitle': 'Ebidensya ken Lokasyon',
    'report.searchLocation': 'Biruken ti lokasyon...',
    'report.tapMap': 'I-tap ti mapa tapno pilien ti lokasyon',
    'report.gpsAutoLocked': 'Automatiko a nakatutok ti lokasyon iti GPS-mo para iti ad-adda a tumpak a report.',
    'report.evidenceLabel': 'Ebidensya',
    'report.photoButton': 'Ladawan',
    'report.videoButton': 'Video',
    'report.evidenceRequired': 'Kasapulan ti ladawan wenno video a kas ebidensya.',
    'report.failedUpload': 'Saan a nai-upload ti ebidensya. Pangngaasi a suriin ti koneksyon ket padasen manen.',
    'report.reviewTitle': 'Suriin ti Report',
    'report.summary': 'Pakabuklan',
    'report.fieldProblem': 'Problema',
    'report.fieldUrgency': 'Urgency/Severity',
    'report.fieldReportedLocation': 'Nairiporda a Lokasyon',
    'report.fieldYourLocation': 'Ti Husto a Lokasyonmo',
    'report.fieldDescription': 'Deskripsyon',
    'report.evidenceCount': 'Ebidensya',
    'report.noEvidence': 'Awan ti naikabil nga ebidensya',
    'report.locationVerification': 'Panangpaneknek ti Lokasyon',
    'report.gpsVerificationRequired': 'Kasapulan ti GPS verification sakbay a maisumite. I-click ti buton dita baba tapno mapaneknekan.',
    'report.verifiedLocationLabel': 'Napaneknekan a Lokasyon:',
    'report.certifyText': 'Paneknekak a pudno ken husto daytoy nga impormasion ken palubosak nga ipatulod ti husto a lokasionko.',
    'report.gpsEnableToSubmit': 'I-enable ti GPS tapno Isumite',
    'report.gpsRequiredTitle': 'Kasapulan ti Lokasyon',
    'report.gpsRequiredBody': 'Tapno maisumite ti report, kasapulan ti Konektizen ti lokasyonmo para iti husto a routing ken response.',
    'report.gpsTurnOnTitle': 'Lukatan ti GPS',
    'report.gpsTurnOnBody': 'Pangngaasi a lukatan ti Location Services (GPS) tapno agtuloy.',
    'report.successTitle': 'Naisumite ti Report!',
    'report.caseLabel': 'Kaso',
    'report.expectedResponse': 'Manamnama nga Oras ti Sungbat',
    'report.responseTimeValue': '24-48 nga Oras',
    'report.thankYou': 'Agyamanak iti panagbalinmo nga aktibo nga umili.',
    'report.backHome': 'Agsubli iti Tahanan',
    'report.tapToSpeak': 'Pinduten tapno Magsarita',
    'report.listening': 'Dengdenggen...',
  },
};
